CREATE DATABASE IF NOT EXISTS db;

USE db;

CREATE TABLE IF NOT EXISTS produto(
    id BIGINT(100) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    idMongo VARCHAR(50) NOT NULL,
    nomeProduto VARCHAR(50) NOT NULL,
    fornecedor VARCHAR(50) NOT NULL,
    valorProduto DOUBLE(10, 2) NOT NULL
);